Add mpulse currency conversion (updated PR)
akamai/edgeworkers-examples pull request #96
Opened 2021-08-25 18:40 UTC by fklasen

This is the new PR for the mPulse example.

2021-08-30 15:20 UTC, mryakan requested changes

2021-08-31 08:11 UTC, fklasen commented on edgekv/examples/mpulse-currency-converter-with-edgekv/main.js
> +      const edgeKv = new EdgeKV({namespace: "name", group: "name"}); //replace name and name with your own values
added the actual names I've used in the implementation

2021-08-31 08:12 UTC, fklasen commented on edgekv/examples/mpulse-currency-converter-with-edgekv/main.js
> +      const edgeKv = new EdgeKV({namespace: "name", group: "name"}); //replace name and name with your own values
done

2021-08-31 08:13 UTC, fklasen commented on edgekv/examples/mpulse-currency-converter-with-edgekv/main.js
> +
fixed

2021-08-31 08:14 UTC, fklasen commented on edgekv/examples/mpulse-currency-converter-with-edgekv/main.js
> +		    'var normalized ='+finalCurrency.value+'*amount;'+
done

2021-08-31 10:50 UTC, fklasen commented on edgekv/examples/mpulse-currency-converter-with-edgekv/main.js
> +	finalCurrency = JSON.parse(finalCurrency)
changed

2021-08-31 10:50 UTC, fklasen commented on edgekv/examples/mpulse-currency-converter-with-edgekv/main.js
> +        return error.toString();
changed

2021-08-31 10:51 UTC, fklasen commented on edgekv/examples/mpulse-currency-converter-with-edgekv/readme.md
> +```javascript
let's remove it for now, I might add the other example later

2021-08-31 10:52 UTC, fklasen commented
all requested changes applied

2021-08-31 19:56 UTC, closed without merging